<?php

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_page_attachments().
 */
function bu_general_features_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'bu_general_features/jquery.migrate';
}

/**
 * Implements hook_js_alter().
 */
function bu_general_features_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  // Ensure jquery-migrate loads right after jquery
  if (isset($javascript['core/assets/vendor/jquery/jquery.min.js'])) {
    $jquery_weight = $javascript['core/assets/vendor/jquery/jquery.min.js']['weight'];
    if (isset($javascript['/libraries/jquery-migrate.min.js'])) {
      $javascript['/libraries/jquery-migrate.min.js']['weight'] = $jquery_weight + 0.001;
    }
  }
}
