mailchimp_transactional_template.mailchimp_transactional_template.*:
  type: config_entity
  label: 'Mailchimp Transactional Template Map config'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: string
      label: 'Label'
    template_name:
      type: string
      label: 'Template name'
    content_area:
      type: string
      label: 'Template region'
    only_use_merge_vars:
      type: boolean
      label: 'Only use merge variables'
    mailsystem_key:
      type: string
      label: 'Email key'
