<?php

/**
 * @file
 * Enables Drupal to send email using Mailchimp Transactional's template system.
 */

declare(strict_types=1);

use Drupal\mailchimp_transactional_template\Entity\TemplateMap;

/**
 * Loads a single Mailchimp Transactional Template Map, or all.
 *
 * @param string|null $id
 *   The ID of the Template Map to load, or null for all.
 *
 * @return array
 *   Array of Template Maps.
 */
function mailchimp_transactional_template_load_entities(string $id = NULL) {
  $query = \Drupal::entityQuery('mailchimp_transactional_template');

  if (!empty($id)) {
    $query->condition('id', $id);
  }

  $map_ids = $query->execute();
  $template_maps = \Drupal::entityTypeManager()
    ->getStorage('mailchimp_transactional_template')
    ->loadMultiple($map_ids);

  return (!empty($id)) ? reset($template_maps) : $template_maps;
}

/**
 * Configures the Mailchimp Transactional Template Map for a mailsystem key.
 *
 * Will search for a default-system mapping if none is available.
 *
 * @param string $module_key
 *   Module key to use when searching for a template mapping.
 * @param string $module
 *   Module name to use when searching for a template mapping.
 *
 * @return \Drupal\mailchimp_transactional_template\Entity\TemplateMap|\entity
 *   The Mailchimp Transactional Template Map, if found.
 */
function mailchimp_transactional_template_load_by_mailsystem($module_key, $module) {
  // Append the default-system condition as a fallback.
  $params = [$module_key, $module, 'default-system'];

  $map_ids = \Drupal::entityQuery('mailchimp_transactional_template')
    ->condition('mailsystem_key', $params, 'IN')
    ->execute();

  $template_maps = TemplateMap::loadMultiple($map_ids);

  $module_match = FALSE;
  if (!empty($template_maps)) {
    /** @var \Drupal\mailchimp_transactional_template\Entity\TemplateMap $map */
    foreach ($template_maps as $template_map) {
      switch ($template_map->mailsystem_key) {
        case $module_key:
          return $template_map;

        case $module:
          $module_match = $template_map;
          break;
      }
    }

    return $module_match ?: reset($template_maps);
  }

  return NULL;
}

/**
 * Get all mailsystem keys pointed at mailchimp_transactional.
 *
 * Includes their template mappings.
 *
 * @return array
 *   Returns an array with indexes matching each module which is assigned
 *   to use Mailchimp Transactional for email sends, and values equal to the
 *   template_map_ids that are assigned to those modules. If no template maps
 *   are assigned, the value is set to NULL.
 */
function mailchimp_transactional_template_usage() {
  $mailsystem_config = \Drupal::service('config.factory')->get('mailsystem.settings');
  $defaults = $mailsystem_config->get('defaults');
  $modules = $mailsystem_config->get('modules');

  $system_assignments = [];

  if (in_array($defaults['sender'], [
    'mailchimp_transactional_mail',
    'mailchimp_transactional_test_mail',
  ])) {
    $system_assignments['default-system'] = NULL;
  }

  if (!empty($modules)) {
    foreach (array_keys($modules) as $module_name) {
      foreach ($modules[$module_name] as $key => $options) {
        if (in_array($options['sender'], [
          'mailchimp_transactional_mail',
          'mailchimp_transactional_test_mail',
        ])) {
          $system_assignments[$module_name . '_' . $key] = NULL;
        }
      }
    }
  }

  $maps = mailchimp_transactional_template_load_entities();
  foreach ($maps as $map) {
    if (isset($map->mailsystem_key) &&
      array_key_exists($map->mailsystem_key, $system_assignments) &&
      isset($map->mailchimp_transactional_template_entity_id)
    ) {
      $system_assignments[$map->mailsystem_key] = $map->mailchimp_transactional_template_entity_id;
    }
  }
  uksort($system_assignments, '_mailchimp_transactional_template_mailsystem_sort');

  return $system_assignments;
}

/**
 * Simple sorting algorithm to organize mailsystems arrays in a logical way.
 *
 * @param string $a
 *   A mailsystem key name.
 * @param string $b
 *   Another mailsystem key name.
 *
 * @return int
 *   Negative if $a should come before $b, else positive.
 */
function _mailchimp_transactional_template_mailsystem_sort($a, $b) {
  $first = 'default-system';
  $last = 'mailchimp_transactional_test';
  if ($a == $first || $b == $last) {
    return -1;
  }
  if ($b == $first || $a == $last) {
    return 1;
  }
  // Otherwise sort alphabetically, case-agnostic.
  return strcasecmp($a, $b);
}
