<?php

/**
 * @file
 * Hooks for media_entity_facebook.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_entity_facebook_help($route_name, RouteMatchInterface $route_match) {
  // To avoid phpmd UnusedFormalParameter errors since there is a fix for that
  // https://github.com/phpmd/phpmd/issues/24
  unset($route_match);
  switch ($route_name) {
    // Main module help for the media_entity_facebook module.
    case 'help.page.media_entity_facebook':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }

    default:
  }
}

/**
 * Implements hook_theme().
 */
function media_entity_facebook_theme($existing, $type, $theme, $path) {
  return [
    'media_entity_facebook' => [
      'variables' => [
        'url' => '',
        'script_attributes' => [],
        'is_iframe' => FALSE,
        'fb_sdk_langcode' => 'en_US',
      ],
    ],
  ];
}
